version: "3"

services:
  gram0:
    container_name: gram0
    build: .
    ports:
      - "1317:1319"
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  gram1:
    container_name: gram1
    build: .
    ports:
      - "1318:1319"
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  gram2:
    container_name: gram2
    build: .
    ports:
      - "1319:1319"
    networks:
      localnet:
        ipv4_address: 192.168.10.4

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24