[package]
name = "ramd-node"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
description = ""

[dependencies]
ramd-processor.workspace = true
ramd-db.workspace = true

eyre.workspace = true
serde.workspace = true
tracing.workspace = true
