[package]
name = "ramd-jsonrpc-types"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
description = ""

[dependencies]
eyre.workspace = true
serde.workspace = true
base64.workspace = true
jsonrpsee.workspace = true
tracing.workspace = true