[package]
name = "ramd-tracing"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
description = ""

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
